FROM node:18

ENV NODE_VERSION 18.18.2

WORKDIR /frontend

COPY . .

RUN npm install -g @angular/cli

RUN npm ci

RUN npm install


RUN npm run build

EXPOSE 4200

CMD ["ng", "serve", "--host", "0.0.0.0", "--port", "4200"]