version: '3'

services:
  frontend:
    build:
      context: ./frontend  
    ports:
      - "4200:4200"

  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=yoel
      - POSTGRES_DB=todo-list
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql


  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db  
    environment:
      - DATABASE_URL=postgresql://postgres:yoel@db:5432/todo-list 

volumes:
  postgres-data:
